<?php

namespace ContainerGMnA5ix;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RGJi08wService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RGJi08w' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RGJi08w'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'groupeRepository' => ['privates', 'App\\Repository\\GroupRepository', 'getGroupRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'groupeRepository' => 'App\\Repository\\GroupRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
