version: '3'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www
    environment:
      APP_ENV: prod
    depends_on:
      - mongodb
    networks:
      - dev

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    environment:
      MONGODB_USER: teamcava
      MONGODB_PASSWORD: lapasserelle
      MONGODB_DB: abattoir_vegetal

networks:
  dev:

volumes:
  database_data:
