<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYIZJdXf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYIZJdXf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYIZJdXf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYIZJdXf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYIZJdXf\App_KernelDevDebugContainer([
    'container.build_hash' => 'YIZJdXf',
    'container.build_id' => 'de8dabd0',
    'container.build_time' => 1689087428,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYIZJdXf');
