<?php

namespace ContainerD6ux6NF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_Type_MongodbDocumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.type.mongodb_document' shared service.
     *
     * @return \Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/doctrine-bridge/Form/Type/DoctrineType.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/mongodb-odm-bundle/Form/Type/DocumentType.php';

        return $container->privates['form.type.mongodb_document'] = new \Doctrine\Bundle\MongoDBBundle\Form\Type\DocumentType(($container->services['doctrine_mongodb'] ?? $container->load('getDoctrineMongodbService')));
    }
}
