<?php

namespace ContainerFyvrtM2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SVvhi_GService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sVvhi.g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sVvhi.g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'documentManager' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'documentManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
