<?php

namespace ContainerFyvrtM2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J_ZDluWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J.zDluW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J.zDluW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::delete' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\AdminController::edit' => ['privates', '.service_locator.sVvhi.g', 'get_ServiceLocator_SVvhi_GService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\AdminController::show' => ['privates', '.service_locator.xawkWJg', 'get_ServiceLocator_XawkWJgService', true],
            'App\\Controller\\ApiUserController::new' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\GroupController::acceptInvitation' => ['privates', '.service_locator.EPAoNd7', 'get_ServiceLocator_EPAoNd7Service', true],
            'App\\Controller\\GroupController::addGroup' => ['privates', '.service_locator.Jm9VFiV', 'get_ServiceLocator_Jm9VFiVService', true],
            'App\\Controller\\GroupController::resa' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\GroupController::resaDate' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\GroupController::select_group' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\GroupController::showUsersList' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\GroupController::showUsersListFull' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\HomeController::home' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.uyc9nKE', 'get_ServiceLocator_Uyc9nKEService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\LoginController::logout' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegisterController::index' => ['privates', '.service_locator.sVvhi.g', 'get_ServiceLocator_SVvhi_GService', true],
            'App\\Controller\\UserProfilController::index' => ['privates', '.service_locator.sVvhi.g', 'get_ServiceLocator_SVvhi_GService', true],
            'App\\Controller\\UserProfilController::success' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\AdminController:delete' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\AdminController:edit' => ['privates', '.service_locator.sVvhi.g', 'get_ServiceLocator_SVvhi_GService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\AdminController:show' => ['privates', '.service_locator.xawkWJg', 'get_ServiceLocator_XawkWJgService', true],
            'App\\Controller\\ApiUserController:new' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\GroupController:acceptInvitation' => ['privates', '.service_locator.EPAoNd7', 'get_ServiceLocator_EPAoNd7Service', true],
            'App\\Controller\\GroupController:addGroup' => ['privates', '.service_locator.Jm9VFiV', 'get_ServiceLocator_Jm9VFiVService', true],
            'App\\Controller\\GroupController:resa' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\GroupController:resaDate' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\GroupController:select_group' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\GroupController:showUsersList' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\GroupController:showUsersListFull' => ['privates', '.service_locator.kQ3e.Yt', 'get_ServiceLocator_KQ3e_YtService', true],
            'App\\Controller\\HomeController:home' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.uyc9nKE', 'get_ServiceLocator_Uyc9nKEService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\LoginController:logout' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'App\\Controller\\RegisterController:index' => ['privates', '.service_locator.sVvhi.g', 'get_ServiceLocator_SVvhi_GService', true],
            'App\\Controller\\UserProfilController:index' => ['privates', '.service_locator.sVvhi.g', 'get_ServiceLocator_SVvhi_GService', true],
            'App\\Controller\\UserProfilController:success' => ['privates', '.service_locator..Ae5NXw', 'get_ServiceLocator__Ae5NXwService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\AdminController::delete' => '?',
            'App\\Controller\\AdminController::edit' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::show' => '?',
            'App\\Controller\\ApiUserController::new' => '?',
            'App\\Controller\\GroupController::acceptInvitation' => '?',
            'App\\Controller\\GroupController::addGroup' => '?',
            'App\\Controller\\GroupController::resa' => '?',
            'App\\Controller\\GroupController::resaDate' => '?',
            'App\\Controller\\GroupController::select_group' => '?',
            'App\\Controller\\GroupController::showUsersList' => '?',
            'App\\Controller\\GroupController::showUsersListFull' => '?',
            'App\\Controller\\HomeController::home' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\LoginController::logout' => '?',
            'App\\Controller\\RegisterController::index' => '?',
            'App\\Controller\\UserProfilController::index' => '?',
            'App\\Controller\\UserProfilController::success' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminController:delete' => '?',
            'App\\Controller\\AdminController:edit' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:show' => '?',
            'App\\Controller\\ApiUserController:new' => '?',
            'App\\Controller\\GroupController:acceptInvitation' => '?',
            'App\\Controller\\GroupController:addGroup' => '?',
            'App\\Controller\\GroupController:resa' => '?',
            'App\\Controller\\GroupController:resaDate' => '?',
            'App\\Controller\\GroupController:select_group' => '?',
            'App\\Controller\\GroupController:showUsersList' => '?',
            'App\\Controller\\GroupController:showUsersListFull' => '?',
            'App\\Controller\\HomeController:home' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\LoginController:logout' => '?',
            'App\\Controller\\RegisterController:index' => '?',
            'App\\Controller\\UserProfilController:index' => '?',
            'App\\Controller\\UserProfilController:success' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
