<?php

namespace ContainerF8a4u7d;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uyc9nKEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uyc9nKE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uyc9nKE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dm' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
            'groupRepository' => ['privates', 'App\\Repository\\GroupRepository', 'getGroupRepositoryService', true],
        ], [
            'dm' => '?',
            'groupRepository' => 'App\\Repository\\GroupRepository',
        ]);
    }
}
