<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentUserHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="bool") */
        if (isset($data['termsAccepted']) || (! empty($this->class->fieldMappings['termsAccepted']['nullable']) && array_key_exists('termsAccepted', $data))) {
            $value = $data['termsAccepted'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['termsAccepted']['type'];
                $return = (bool) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['termsAccepted']->setValue($document, $return);
            $hydratedData['termsAccepted'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['username']) || (! empty($this->class->fieldMappings['username']['nullable']) && array_key_exists('username', $data))) {
            $value = $data['username'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['username']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['username']->setValue($document, $return);
            $hydratedData['username'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['email']) || (! empty($this->class->fieldMappings['email']['nullable']) && array_key_exists('email', $data))) {
            $value = $data['email'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['email']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['email']->setValue($document, $return);
            $hydratedData['email'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['password']) || (! empty($this->class->fieldMappings['password']['nullable']) && array_key_exists('password', $data))) {
            $value = $data['password'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['password']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['password']->setValue($document, $return);
            $hydratedData['password'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['city']) || (! empty($this->class->fieldMappings['city']['nullable']) && array_key_exists('city', $data))) {
            $value = $data['city'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['city']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['city']->setValue($document, $return);
            $hydratedData['city'] = $return;
        }

        /** @Field(type="int") */
        if (isset($data['age']) || (! empty($this->class->fieldMappings['age']['nullable']) && array_key_exists('age', $data))) {
            $value = $data['age'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['age']['type'];
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['age']->setValue($document, $return);
            $hydratedData['age'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['gender']) || (! empty($this->class->fieldMappings['gender']['nullable']) && array_key_exists('gender', $data))) {
            $value = $data['gender'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['gender']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['gender']->setValue($document, $return);
            $hydratedData['gender'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['language']) || (! empty($this->class->fieldMappings['language']['nullable']) && array_key_exists('language', $data))) {
            $value = $data['language'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['language']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['language']->setValue($document, $return);
            $hydratedData['language'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['flagIconUrl']) || (! empty($this->class->fieldMappings['flagIconUrl']['nullable']) && array_key_exists('flagIconUrl', $data))) {
            $value = $data['flagIconUrl'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['flagIconUrl']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['flagIconUrl']->setValue($document, $return);
            $hydratedData['flagIconUrl'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['image']) || (! empty($this->class->fieldMappings['image']['nullable']) && array_key_exists('image', $data))) {
            $value = $data['image'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['image']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['image']->setValue($document, $return);
            $hydratedData['image'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['job']) || (! empty($this->class->fieldMappings['job']['nullable']) && array_key_exists('job', $data))) {
            $value = $data['job'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['job']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['job']->setValue($document, $return);
            $hydratedData['job'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['description']) || (! empty($this->class->fieldMappings['description']['nullable']) && array_key_exists('description', $data))) {
            $value = $data['description'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['description']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['description']->setValue($document, $return);
            $hydratedData['description'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['diet']) || (! empty($this->class->fieldMappings['diet']['nullable']) && array_key_exists('diet', $data))) {
            $value = $data['diet'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['diet']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['diet']->setValue($document, $return);
            $hydratedData['diet'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['centerOfInterestPerso']) || (! empty($this->class->fieldMappings['centerOfInterestPerso']['nullable']) && array_key_exists('centerOfInterestPerso', $data))) {
            $value = $data['centerOfInterestPerso'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['centerOfInterestPerso']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['centerOfInterestPerso']->setValue($document, $return);
            $hydratedData['centerOfInterestPerso'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['centerOfInterest']) || (! empty($this->class->fieldMappings['centerOfInterest']['nullable']) && array_key_exists('centerOfInterest', $data))) {
            $value = $data['centerOfInterest'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['centerOfInterest']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['centerOfInterest']->setValue($document, $return);
            $hydratedData['centerOfInterest'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['roles']) || (! empty($this->class->fieldMappings['roles']['nullable']) && array_key_exists('roles', $data))) {
            $value = $data['roles'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['roles']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['roles']->setValue($document, $return);
            $hydratedData['roles'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['postalCode']) || (! empty($this->class->fieldMappings['postalCode']['nullable']) && array_key_exists('postalCode', $data))) {
            $value = $data['postalCode'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['postalCode']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['postalCode']->setValue($document, $return);
            $hydratedData['postalCode'] = $return;
        }
        return $hydratedData;
    }
}