<?php

namespace ContainerE9wem98;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Document\User' shared autowired service.
     *
     * @return \App\Document\User
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Document'.\DIRECTORY_SEPARATOR.'User.php';

        return $container->privates['App\\Document\\User'] = new \App\Document\User();
    }
}
