<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE9wem98\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE9wem98/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerE9wem98.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerE9wem98\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerE9wem98\App_KernelTestDebugContainer([
    'container.build_hash' => 'E9wem98',
    'container.build_id' => '5ef5183c',
    'container.build_time' => 1691494227,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE9wem98');
