<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_admin_index' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin/']], [], [], []],
    'app_admin_show' => [['id'], ['_controller' => 'App\\Controller\\AdminController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin']], [], [], []],
    'app_admin_edit' => [['id'], ['_controller' => 'App\\Controller\\AdminController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/edit']], [], [], []],
    'app_admin_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/delete']], [], [], []],
    'app_admin_grpindex' => [[], ['_controller' => 'App\\Controller\\AdminGroupController::index'], [], [['text', '/adminGrp/']], [], [], []],
    'app_grpadmin_delete' => [['id'], ['_controller' => 'App\\Controller\\AdminGroupController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/adminGrp/deleteGrp']], [], [], []],
    'app_api_user' => [[], ['_controller' => 'App\\Controller\\ApiUserController::new'], [], [['text', '/api_user']], [], [], []],
    'app_select_group' => [[], ['_controller' => 'App\\Controller\\GroupController::select_group'], [], [['text', '/group/select_group']], [], [], []],
    'app_get_users_list_without_filters' => [[], ['_controller' => 'App\\Controller\\GroupController::showUsersListFull'], [], [['text', '/group/users-list/']], [], [], []],
    'app_add_group' => [['idUsers', 'date'], ['_controller' => 'App\\Controller\\GroupController::addGroup'], [], [['variable', '/', '[^/]++', 'date', true], ['variable', '/', '[^/]++', 'idUsers', true], ['text', '/group/add']], [], [], []],
    'app_get_users_list_from_filters' => [['filters'], ['_controller' => 'App\\Controller\\GroupController::showUsersList'], [], [['variable', '/', '[^/]++', 'filters', true], ['text', '/group/users-list']], [], [], []],
    'accept_Invitation' => [['id', 'bool'], ['_controller' => 'App\\Controller\\GroupController::acceptInvitation'], [], [['variable', '/', '[^/]++', 'bool', true], ['variable', '/', '[^/]++', 'id', true], ['text', '/group/accept']], [], [], []],
    'app_invitation' => [[], ['_controller' => 'App\\Controller\\GroupController::invitation'], [], [['text', '/group/invitation']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::home'], [], [['text', '/']], [], [], []],
    'app_home_help' => [[], ['_controller' => 'App\\Controller\\HomeController::help'], [], [['text', '/help']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\LoginController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\LoginController::logout'], [], [['text', '/logout']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/register/add']], [], [], []],
    'reservation_page' => [[], ['_controller' => 'App\\Controller\\ReservationController::reservationPage'], [], [['text', '/reservation/']], [], [], []],
    'app_reservation' => [[], ['_controller' => 'App\\Controller\\ReservationController::allReservations'], [], [['text', '/reservation/allReservation']], [], [], []],
    'app_userapp_user' => [[], ['_controller' => 'App\\Controller\\UserController::index'], [], [['text', '/user/s']], [], [], []],
    'app_user_profil' => [[], ['_controller' => 'App\\Controller\\UserProfilController::index'], [], [['text', '/user_profil/edit']], [], [], []],
    'app_user_profil_success' => [[], ['_controller' => 'App\\Controller\\UserProfilController::success'], [], [['text', '/user_profil/profil']], [], [], []],
];
