<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAobGkQT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAobGkQT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAobGkQT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAobGkQT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAobGkQT\App_KernelDevDebugContainer([
    'container.build_hash' => 'AobGkQT',
    'container.build_id' => '8e05f3db',
    'container.build_time' => 1689858401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAobGkQT');
