<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7CXeBNj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7CXeBNj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7CXeBNj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7CXeBNj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7CXeBNj\App_KernelDevDebugContainer([
    'container.build_hash' => '7CXeBNj',
    'container.build_id' => 'd4f5b8b7',
    'container.build_time' => 1689885526,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7CXeBNj');
