<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVeyuqLN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVeyuqLN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVeyuqLN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVeyuqLN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVeyuqLN\App_KernelDevDebugContainer([
    'container.build_hash' => 'VeyuqLN',
    'container.build_id' => '73be7480',
    'container.build_time' => 1689182749,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVeyuqLN');
